### ISSUE TITLE
Contract tab is broken

### ISSUE THREAD

**Issue by isopen** [catchain/tonscan#49]
### Bug Type

UI/UX

### Reproduction steps

[vokoscreenNG-2022-09-21_05-13-27.webm](https://user-images.githubusercontent.com/7373292/191378420-1f0451ba-2603-4370-8b34-d7b7b40d9028.webm)

### Actual result

Extra table renderings when there is nothing.

### Expected result

In serious applications, this should not work.
Fix the application life cycle.

### Suggested Severity

Critical

### Device

Desktop (please complete the following information):
- OS: Ubuntu 22
- Browser Google Chrome
- Version 105.0.5195.52

**Comment by ingria** [comment]
I can't see how application lifecycle has something to do with this error.

Dupe #41

**Comment by isopen** [comment]
> I can't see how application lifecycle has something to do with this error.
> 
> Dupe #41

@ingria This is not a duplicate of #41.

**Comment by ingria** [comment]
This is called “preloader” or “[skeleton](https://dev.to/shantanu_jana/skeleton-screen-loading-animation-using-html-css-1ec3)” and it indicates that the app is loading data. Skeleton is **always** shown until the ajax request resolves (either with error or with data).

The only problem that I see here is that skeleton doesn’t disappear on inactive address “contract” tab because of api error.

I’ve changed the title because this problem has nothing to do with application lifecycle. If you think I’m wrong, please explain where exactly in the lifecycle there’s an error.

**Comment by isopen** [comment]
@ingria Thanks. Your comment is great.

1. In the case of an ajax request, you can first get the data.
2. In the process of receiving data, show the loader.
3. Draw the table itself along with the data.

This strategy should ensure that the view is visually static.

**Comment by ingria** [comment]
"Skeleton" is just another type of loader. It is not rotating and round, yet it is still some entity indicating that the data is loading.

Unfortunately, displaying round spinning loader is not an option, because every page loads data from several different places (APIs). Some data is fast to fetch (like balance), some is slow (like contract type). Notice, how different "skeletons" take different amount of time to load: 

https://user-images.githubusercontent.com/2178368/192103911-6a92a074-e6ba-4b0a-8747-55e063e82050.mp4

Displaying many spinning loaders would not look nice. Also, for the same reason we cannot display one big loader and wait until **all** data on the page is loaded - it would take too much time. Better display piece of info when it's ready, right away.

**Comment by isopen** [comment]
You can try to make a loader for the first start of the table. I considered the case of the first entry to the page (the case of reloading the page on the browser button).
This can reduce flickering when the table is first started?
